version: "3.8"

volumes:
  artistry-codex-volume:

services:
  db:
    image: postgres
    volumes:
      - artistry-codex-volume:/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: artistry-codex-client
    command: "serve"
    volumes:
      - .:/code
    ports:
      - "${LOCAL_WEBPACK_SERVER_PORT}:8080"
    environment:
      LOCAL_WEBPACK_SERVER_PORT: "${LOCAL_WEBPACK_SERVER_PORT}"
      DEVSERVER_HOST: "${DEVSERVER_HOST:-localhost}"

  web:
    build: .
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db