version: "3.8"

volumes:
  artistry-codex-volume:

services:
  db:
    image: postgres
    volumes:
      - artistry-codex-volume:/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-root}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-root}"
      POSTGRES_DB: "${POSTGRES_DB:-local}"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: artistry-codex-client
    command: "build"
    volumes:
      - .:/code

  web:
    build: .
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-root}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-root}"
      POSTGRES_DB: "${POSTGRES_DB:-local}"
      POSTGRES_HOST: "${POSTGRES_HOST:-db}"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db