# Generated by Django 3.1.2 on 2020-10-29 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('instagram_url', models.CharField(max_length=200)),
                ('instagram_username', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_code', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('uf', models.CharField(max_length=2)),
                ('region', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('artists', models.ManyToManyField(to='artists.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.states'),
        ),
    ]
