# Generated by Django 3.1.3 on 2020-11-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20201029_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='instagram_url',
            new_name='portfolio',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='url',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='artists',
        ),
        migrations.AddField(
            model_name='artist',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(default='Brazil', max_length=200),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.state'),
        ),
        migrations.RemoveField(
            model_name='artist',
            name='tags',
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.tag'),
        ),
    ]
