# Generated by Django 3.1.3 on 2020-11-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20201104_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='country',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='tags',
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='artists.Tag'),
        ),
    ]
