# Generated by Django 3.2.3 on 2021-05-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20201104_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='artists.Tag'),
        ),
    ]
